# Generated by Django 6.0.6 on 2026-07-17 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationImageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query', models.CharField(max_length=500)),
                ('provider', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('attribution_text', models.CharField(blank=True, max_length=500)),
                ('attribution_url', models.URLField(blank=True, max_length=1000)),
                ('destination_id', models.CharField(blank=True, max_length=100)),
                ('license', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=200)),
                ('destination_canonical', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('num_days', models.PositiveIntegerField(default=3)),
                ('budget_inr', models.PositiveIntegerField(default=0)),
                ('group_size', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('adventure', 'Adventure'), ('family', 'Family'), ('honeymoon', 'Honeymoon'), ('food', 'Food'), ('spiritual', 'Spiritual'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('complete', 'Complete'), ('paid', 'Paid'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('origin_city', models.CharField(blank=True, max_length=100)),
                ('hotel_pref', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('amount_paise', models.PositiveIntegerField(default=9900)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='CostLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('llm_cost_usd', models.FloatField(default=0.0)),
                ('api_cost_usd', models.FloatField(default=0.0)),
                ('provider_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_logs', to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list)),
                ('graph_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('overall_confidence', models.JSONField(blank=True, default=dict)),
                ('itinerary_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.trip')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('trip', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('place_name', models.CharField(max_length=300)),
                ('place_type', models.CharField(choices=[('attraction', 'Attraction'), ('food', 'Food'), ('hotel', 'Hotel'), ('transit', 'Transit'), ('activity', 'Activity')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost_inr', models.PositiveIntegerField(default=0)),
                ('maps_url', models.URLField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('visual_metadata', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.JSONField(blank=True, default=dict)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tripversion')),
            ],
            options={
                'ordering': ['day_number', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
