"""
services/pdf.py — PDF generation service with automatic mock/offline mode.

If the weasyprint package is unavailable, a readable plain-text ``.txt``
itinerary file is generated instead of a PDF.
"""

import logging
import tempfile
from io import StringIO

logger = logging.getLogger('agent')

# ── Mock-mode detection ───────────────────────────────────────────────────────
MOCK_MODE = False

try:
    from weasyprint import HTML
    logger.info('[pdf] WeasyPrint loaded — PDF generation available.')
except Exception as e:
    MOCK_MODE = True
    HTML = None
    logger.warning(
        f'[pdf] weasyprint package unavailable ({e}) — activating MOCK PDF mode. '
        'Itineraries will be exported as plain-text files.'
    )


# ── Public API ────────────────────────────────────────────────────────────────

def generate_trip_pdf(trip, days: dict) -> str:
    """Generate an itinerary document for the trip.

    Returns the path to the generated file — a ``.pdf`` in live mode or a
    nicely formatted ``.txt`` in mock mode.
    """
    total_cost = sum(
        item.cost_inr for day_items in days.values() for item in day_items
    )

    if MOCK_MODE:
        return _generate_text_itinerary(trip, days, total_cost)

    return _generate_pdf(trip, days, total_cost)


# ── Private helpers ───────────────────────────────────────────────────────────

def _generate_text_itinerary(trip, days: dict, total_cost: int) -> str:
    """Create a human-readable plain-text itinerary file."""
    buf = StringIO()
    separator = '=' * 60

    buf.write(f'{separator}\n')
    buf.write(f'  TripMind AI — Trip Itinerary\n')
    buf.write(f'{separator}\n\n')
    buf.write(f'  Destination : {trip.destination}\n')
    buf.write(f'  Duration    : {trip.num_days} days\n')
    if trip.start_date:
        buf.write(f'  Start Date  : {trip.start_date}\n')
    if getattr(trip, 'origin_city', None):
        buf.write(f'  Origin      : {trip.origin_city}\n')
    buf.write(f'  Budget      : ₹{trip.budget_inr:,}\n')
    buf.write(f'\n{separator}\n')
    buf.write(f'  DAY-BY-DAY ITINERARY\n')
    buf.write(f'{separator}\n\n')

    for day_num, items in sorted(days.items()):
        buf.write(f'  ── Day {day_num} {"─" * 45}\n\n')
        for item in items:
            time_str = ''
            if item.start_time:
                time_str = item.start_time.strftime('%H:%M')
            if item.end_time:
                time_str += f' – {item.end_time.strftime("%H:%M")}'
            if time_str:
                buf.write(f'    {time_str}\n')
            buf.write(f'    {item.place_name}\n')
            if item.description:
                buf.write(f'    {item.description}\n')
            buf.write(f'    Cost: ₹{item.cost_inr:,}\n')
            buf.write('\n')

    buf.write(f'{separator}\n')
    buf.write(f'  TOTAL ESTIMATED COST: ₹{total_cost:,}\n')
    buf.write(f'{separator}\n')
    buf.write(f'\n  Generated by TripMind AI | tripmind.ai\n')

    tmp = tempfile.NamedTemporaryFile(
        mode='w', suffix='.txt', delete=False, encoding='utf-8'
    )
    tmp.write(buf.getvalue())
    tmp.close()

    logger.info(f'[pdf] Mock text itinerary generated for trip {trip.pk} at {tmp.name}')
    return tmp.name


def _generate_pdf(trip, days: dict, total_cost: int) -> str:
    """Render the HTML template and produce a PDF via WeasyPrint."""
    from django.template.loader import render_to_string

    html_string = render_to_string('itinerary_pdf.html', {
        'trip': trip,
        'days': days,
        'total_cost': total_cost,
    })
    tmp = tempfile.NamedTemporaryFile(suffix='.pdf', delete=False)
    HTML(string=html_string).write_pdf(tmp.name)
    logger.info(f'[pdf] Generated PDF for trip {trip.pk} at {tmp.name}')
    return tmp.name
